// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.accounts */
export type AccountsId = string & { __brand: 'AccountsId' };

/** Represents the table public.accounts */
export default interface AccountsTable {
  id: ColumnType<AccountsId, AccountsId | undefined, AccountsId>;

  name: ColumnType<string, string, string>;

  created: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Accounts = Selectable<AccountsTable>;

export type NewAccounts = Insertable<AccountsTable>;

export type AccountsUpdate = Updateable<AccountsTable>;
