// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type AccountsId } from './Accounts';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.journals */
export type JournalsId = string & { __brand: 'JournalsId' };

/** Represents the table public.journals */
export default interface JournalsTable {
  id: ColumnType<JournalsId, JournalsId | undefined, JournalsId>;

  account_id: ColumnType<AccountsId | null, AccountsId | null, AccountsId | null>;

  amount: ColumnType<string, string, string>;

  created: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Journals = Selectable<JournalsTable>;

export type NewJournals = Insertable<JournalsTable>;

export type JournalsUpdate = Updateable<JournalsTable>;
