// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.schema_migrations */
export type SchemaMigrationsVersion = string & { __brand: 'SchemaMigrationsVersion' };

/** Represents the table public.schema_migrations */
export default interface SchemaMigrationsTable {
  version: ColumnType<SchemaMigrationsVersion, SchemaMigrationsVersion, SchemaMigrationsVersion>;

  dirty: ColumnType<boolean, boolean, boolean>;
}

export type SchemaMigrations = Selectable<SchemaMigrationsTable>;

export type NewSchemaMigrations = Insertable<SchemaMigrationsTable>;

export type SchemaMigrationsUpdate = Updateable<SchemaMigrationsTable>;
